name: sio113-2021-py3
channels:
  - defaults
  - conda-forge
dependencies:
  - python=3.8
  - future=0.18.2
  - numpy=1.20.1
  - scipy=1.6.1
  - matplotlib=3.3.4
  - pandas=1.2.3
  - scikit-learn=0.24.1
  - geopandas=0.9.0
  - geoplot=0.4.1
  - cartopy=0.18.0
  - seaborn=0.11.1
  - imageio=2.9.0
  - lmfit=1.0.2
  - pyqt=5.12.3
  - xlwt=1.3.0
  - xlrd=2.0.1
  - openpyxl=3.0.7
