name: ppfess-environment
channels:
  - defaults
  - conda-forge
dependencies:
  - python=3.6
  - future=0.16.0
  - numpy=1.14.0
  - matplotlib=2.2.3
  - pandas=0.23.1
  - scipy=1.0.0
  - cartopy=0.17.0
  - pyqt=5.9.2
  - lmfit=0.9.11
  - scikit-learn=0.20.0
  - xlwt=1.2.0
  - seaborn=0.9.0
  - imageio=2.4.1
  - geopandas=0.7.0
  - descartes=1.1.0
